services:
  backend:
    build: ./backend
    container_name: scalestorm-backend
    ports:
      - '3001:3001'
    networks:
      - scalestorm-network
    restart: unless-stopped

  frontend:
    build: ./front
    container_name: scalestorm-frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
    networks:
      - scalestorm-network
    restart: unless-stopped

networks:
  scalestorm-network:
    driver: bridge
